name: Auto Deploy

on:
  push:
      branches: [main]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: yarn
        - uses: redkubes/docusaurus-deploy-action@v1
          with:
            source-folder: ./
            git-user: anvie
            git-password: ${{ secrets.GH_PAGES_TOKEN }}
            deployment-branch: gh-pages
