name: Auto Deploy

on:
  push:
      branches: [main]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install Yarn
          run: npm install -g yarn
        - name: Deploying
          run: |
            git config --global user.email "nuid-docs-deploy@users.noreply.github.com"
            git config --global user.name "NUID Docs CI"
            echo "machine github.com login neuversity password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
            yarn && GIT_USER=neuversity PUBLISHING=true yarn deploy
