name: Auto Deploy

on:
  push:
      branches: [main]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install Yarn
          run: npm install -g yarn
        - name: Deploying
          run: |
            git config --global user.email "nu-id-doc-deploy@users.noreply.github.com"
            git config --global user.name "NU.ID Doc Deploy"
            echo "machine github.com login anvie password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
            yarn && GIT_USER=anvie PUBLISHING=true yarn deploy
