name: Auto Deploy

on:
  push:
      branches: [main]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install Yarn
          run: npm install -g yarn
        - run: yarn install
        - run: yarn build
        - uses: peaceiris/actions-gh-pages@v2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
