name: Auto Deploy

on:
  push:
      branches: [main]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: redkubes/docusaurus-deploy-action@v1
          with:
            source-folder: build
            git-user: anvie
            git-password: ${{ secrets.GH_PAGES_TOKEN }}
            deployment-branch: gh-pages
